version: "3.8"

volumes:
  redis:

services: 
  redis:
    image: redis:alpine3.14
    container_name: redis
    restart: always
    volumes: 
     - redis:/data
    ports:
     - 6379:6379
    command: redis-server --appendonly yes
  
  redis_php_fpm:
    image: registry.scaip.com.br/scaip_voip/huller_push_voip_redis_php_fpm@sha256:b17348698e69faa024bcac58bd0b2e313e39f65adc837299f21232cab9eb56d7
    container_name: redis_php_fpm
    restart: always
    volumes:
     - ./volumes:/public
    depends_on: 
     - redis
  
  redis_webserver:
    build: ./redis_webserver
    container_name: redis_webserver
    restart: always
    volumes:
     - public:/public
    ports:
     - 3030:8080
    volumes:
     - ./volumes:/public
    depends_on: 
     - redis
