version: "3.8"
services: 
  redis:
    image: redis:alpine3.14
    container_name: redis
    restart: always
    ports:
    - 6379:6379
  push_api:
    build: ./redis_api
    container_name: redis_api
    restart: always
    ports: 
      - 3030:80
    depends_on: 
      - redis
    command: ["/usr/sbin/httpd", "-D", "FOREGROUND"]
