FROM php:7.3-fpm-alpine
# ENV TZ=America/Recife
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
# apk --no-cache add pcre-dev ${PHPIZE_DEPS} \
# && printf "\n" | pecl install redis \
# && docker-php-ext-enable redis \
# && apk del pcre-dev ${PHPIZE_DEPS} \
# && rm -rf /tmp/pear